name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            artifact-name: ubuntu-latest-artifact
            path: |
              src-tauri/target/release/bundle/deb/*.deb
              src-tauri/target/release/bundle/appimage/*.AppImage
              src-tauri/target/release/bundle/appimage/*.AppImage.tar.gz
              src-tauri/target/release/bundle/appimage/*.AppImage.tar.gz.sig
          - os: macos-latest
            artifact-name: macos-latest-artifact
            path: |
              src-tauri/target/release/bundle/dmg/*.dmg
              src-tauri/target/release/bundle/macos/*.app.zip
              src-tauri/target/release/bundle/macos/*.app.tar.gz
              src-tauri/target/release/bundle/macos/*.app.tar.gz.sig
          - os: windows-latest
            artifact-name: windows-latest-artifact
            path: |
              src-tauri/target/release/bundle/msi/*.msi
              src-tauri/target/release/bundle/msi/*.msi.zip
              src-tauri/target/release/bundle/msi/*.msi.zip.sig
              src-tauri/target/release/bundle/nsis/*.exe
              src-tauri/target/release/bundle/nsis/*.nsis.zip
              src-tauri/target/release/bundle/nsis/*.nsis.zip.sig

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - name: Setup webkit2gtk (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Create Release
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: |
          pnpm install
          pnpm run tauri:build

      - name: Zip Artifact (macos only)
        if: matrix.os == 'macos-latest'
        run: |
          cd src-tauri/target/release/bundle/macos
          zip -r DepositBox.app.zip *.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.path }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          files: ${{ matrix.path }}
          token: ${{ secrets.GH_TOKEN }}
